import type { Metadata } from 'next'
import { Amatic_SC, Quicksand } from 'next/font/google'
import '@/styles/main.scss'
import HeaderNav from '@/components/HeaderNav/HeaderNav'
import Footer from '@/components/Footer/Footer'

const quicksand = Quicksand({
  subsets: ['latin'],
})

const amatic = Amatic_SC({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout ({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} ${amatic.className}`}>
        <div className="appLayout">
          <HeaderNav />
          <main>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
